name: insect-model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scipy
  - qutip
  - pip
  - pip:
      - jupyterlab          # optional but very useful for notebooks
